#!/usr/bin/env python3


team_codes = frozenset(
        ["AFC", "ARI", "ATL", "BAL", "BUF", "CAR", "CHI", "CIN", "CLE", "DAL",
            "DEN", "DET", "GB", "HOU", "IND", "JAC", "KC", "MIA", "MIN", "NE",
            "NO", "NFC", "NYG", "NYJ", "OAK", "PHI", "PIT", "SD", "SEA", "SF",
            "STL", "TB", "TEN", "WAS"]
        )

pfr_codes = frozenset(
        ["CRD", "ATL", "RAV", "BUF", "CAR", "CHI", "CIN", "CLE", "DAL", "DEN",
            "DET", "GNB", "HTX", "CLT", "JAX", "KAN", "MIA", "MIN", "NWE",
            "NOR", "NYG", "NYJ", "RAI", "PHI", "PIT", "SDG", "SFO", "SEA",
            "RAM", "TAM", "OTI", "WAS"]
        )

team_names = frozenset(
        ["AFC Probowl Team", "Arizona Cardinals", "Atlanta Falcons",
            "Baltimore Ravens", "Buffalo Bills", "Carolina Panthers",
            "Chicago Bears", "Cincinnati Bengals", "Cleveland Browns",
            "Dallas Cowboys", "Denver Broncos", "Detroit Lions",
            "Green Bay Packers", "Houston Texans", "Indianapolis Colts",
            "Jacksonville Jaguars", "Kansas City Chiefs", "Miami Dolphins",
            "Minnesota Vikings", "New England Patriots", "New Orleans Saints",
            "NFC Probowl Team", "New York Giants", "New York Jets",
            "Oakland Raiders", "Philadelphia Eagles", "Pittsburgh Steelers",
            "San Diego Chargers", "Seattle Seahawks", "San Francisco 49ers",
            "Saint Louis Rams", "St. Louis Rams", "Tampa Bay Buccaneers",
            "Tennessee Titans", "Washington Redskins"]
        )

codes_to_name = {
        "AFC": "AFC Probowl Team",
        "ARI": "Arizona Cardinals",
        "ATL": "Atlanta Falcons",
        "BAL": "Baltimore Ravens",
        "BUF": "Buffalo Bills",
        "CAR": "Carolina Panthers",
        "CHI": "Chicago Bears",
        "CIN": "Cincinnati Bengals",
        "CLE": "Cleveland Browns",
        "DAL": "Dallas Cowboys",
        "DEN": "Denver Broncos",
        "DET": "Detroit Lions",
        "GB": " Green Bay Packers",
        "HOU": "Houston Texans",
        "IND": "Indianapolis Colts",
        "JAC": "Jacksonville Jaguars",
        "KC": " Kansas City Chiefs",
        "MIA": "Miami Dolphins",
        "MIN": "Minnesota Vikings",
        "NE": "New England Patriots",
        "NO": "New Orleans Saints",
        "NFC": "NFC Probowl Team",
        "NYG": "New York Giants",
        "NYJ": "New York Jets",
        "OAK": "Oakland Raiders",
        "PHI": "Philadelphia Eagles",
        "PIT": "Pittsburgh Steelers",
        "SD": "San Diego Chargers",
        "SEA": "Seattle Seahawks",
        "SF": "San Francisco 49ers",
        "STL": "Saint Louis Rams",
        "TB": "Tampa Bay Buccaneers",
        "TEN": "Tennessee Titans",
        "WAS": "Washington Redskins"
        }

names_to_code = {
        "AFC Probowl Team": "AFC",
        "Arizona Cardinals": "ARI",
        "Atlanta Falcons": "ATL",
        "Baltimore Ravens": "BAL",
        "Buffalo Bills": "BUF",
        "Carolina Panthers": "CAR",
        "Chicago Bears": "CHI",
        "Cincinnati Bengals": "CIN",
        "Cleveland Browns": "CLE",
        "Dallas Cowboys": "DAL",
        "Denver Broncos": "DEN",
        "Detroit Lions": "DET",
        "Green Bay Packers": "GB",
        "Houston Texans": "HOU",
        "Indianapolis Colts": "IND",
        "Jacksonville Jaguars": "JAC",
        "Kansas City Chiefs": "KC",
        "Miami Dolphins": "MIA",
        "Minnesota Vikings": "MIN",
        "New England Patriots": "NE",
        "New Orleans Saints": "NO",
        "NFC Probowl Team": "NFC",
        "New York Giants": "NYG",
        "New York Jets": "NYJ",
        "Oakland Raiders": "OAK",
        "Philadelphia Eagles": "PHI",
        "Pittsburgh Steelers": "PIT",
        "San Diego Chargers": "SD",
        "Seattle Seahawks": "SEA",
        "San Francisco 49ers": "SF",
        "Saint Louis Rams": "STL",
        "St. Louis Rams": "STL",
        "Tampa Bay Buccaneers": "TB",
        "Tennessee Titans": "TEN",
        "Washington Redskins": "WAS",
        }

pfr_codes_to_code = {
        "CRD": "ARI",
        "ATL": "ATL",
        "RAV": "BAL",
        "BUF": "BUF",
        "CAR": "CAR",
        "CHI": "CHI",
        "CIN": "CIN",
        "CLE": "CLE",
        "DAL": "DAL",
        "DEN": "DEN",
        "DET": "DET",
        "GNB": "GB",
        "HTX": "HOU",
        "CLT": "IND",
        "JAX": "JAC",
        "KAN": "KC",
        "MIA": "MIA",
        "MIN": "MIN",
        "NWE": "NE",
        "NOR": "NO",
        "NYG": "NYG",
        "NYJ": "NYJ",
        "RAI": "OAK",
        "PHI": "PHI",
        "PIT": "PIT",
        "SDG": "SD",
        "SFO": "SEA",
        "SEA": "SF",
        "RAM": "STL",
        "TAM": "TB",
        "OTI": "TEN",
        "WAS": "WAS",
        }
