#!/usr/bin/env python3


team_codes = frozenset(
        ["AFC", "ARI", "ATL", "BAL", "BUF", "CAR", "CHI", "CIN", "CLE", "DAL",
            "DEN", "DET", "GB", "HOU", "IND", "JAC", "KC", "MIA", "MIN", "NE",
            "NO", "NFC", "NYG", "NYJ", "OAK", "PHI", "PIT", "SD", "SEA", "SF",
            "STL", "TB", "TEN", "WAS"]
        )

codes_to_name = {
        "AFC": "AFC Probowl Team",
        "ARI": "Arizona Cardinals",
        "ATL": "Atlanta Falcons",
        "BAL": "Baltimore Ravens",
        "BUF": "Buffalo Bills",
        "CAR": "Carolina Panthers",
        "CHI": "Chicago Bears",
        "CIN": "Cincinnati Bengals",
        "CLE": "Cleveland Browns",
        "DAL": "Dallas Cowboys",
        "DEN": "Denver Broncos",
        "DET": "Detroit Lions",
        "GB": " Green Bay Packers",
        "HOU": "Houston Texans",
        "IND": "Indianapolis Colts",
        "JAC": "Jacksonville Jaguars",
        "KC": " Kansas City Chiefs",
        "MIA": "Miami Dolphins",
        "MIN": "Minnesota Vikings",
        "NE": "New England Patriots",
        "NO": "New Orleans Saints",
        "NFC": "NFC Probowl Team",
        "NYG": "New York Giants",
        "NYJ": "New York Jets",
        "OAK": "Oakland Raiders",
        "PHI": "Philadelphia Eagles",
        "PIT": "Pittsburgh Steelers",
        "SD": "San Diego Chargers",
        "SEA": "Seattle Seahawks",
        "SF": "San Francisco 49ers",
        "STL": "Saint Louis Rams",
        "TB": "Tampa Bay Buccaneers",
        "TEN": "Tennessee Titans",
        "WAS": "Washington Redskins"
        }

names_to_code = {
        "AFC Probowl Team": "AFC",
        "Arizona Cardinals": "ARI",
        "Atlanta Falcons": "ATL",
        "Baltimore Ravens": "BAL",
        "Buffalo Bills": "BUF",
        "Carolina Panthers": "CAR",
        "Chicago Bears": "CHI",
        "Cincinnati Bengals": "CIN",
        "Cleveland Browns": "CLE",
        "Dallas Cowboys": "DAL",
        "Denver Broncos": "DEN",
        "Detroit Lions": "DET",
        "Green Bay Packers": "GB",
        "Houston Texans": "HOU",
        "Indianapolis Colts": "IND",
        "Jacksonville Jaguars": "JAC",
        "Kansas City Chiefs": "KC",
        "Miami Dolphins": "MIA",
        "Minnesota Vikings": "MIN",
        "New England Patriots": "NE",
        "New Orleans Saints": "NO",
        "NFC Probowl Team": "NFC",
        "New York Giants": "NYG",
        "New York Jets": "NYJ",
        "Oakland Raiders": "OAK",
        "Philadelphia Eagles": "PHI",
        "Pittsburgh Steelers": "PIT",
        "San Diego Chargers": "SD",
        "Seattle Seahawks": "SEA",
        "San Francisco 49ers": "SF",
        "Saint Louis Rams": "STL",
        "Tampa Bay Buccaneers": "TB",
        "Tennessee Titans": "TEN",
        "Washington Redskins": "WAS",
        }
